server:
  public_addr: ":443"
  domain_base: "getexposed.io"
  admin:
    enable: true
    token: "change-me-admin-token"
  tenancy:
    enable: true
    storage: "/etc/drill/tenants.json"
  acme:
    enable: false
    email: "you@example.com"
    cache: "/var/lib/drill-acme"
    challenge: "http-01"     # or "dns-01"
    dns_provider: ""         # set when challenge=dns-01 (cloudflare/route53)
    ca: "letsencrypt"        # or "staging"
sni:
  enable: true
  addr: ":8443"
