server:
  public: ":443"
  domain_base: "getexposed.io"
  acme:
    enable: true
    email: "you@example.com"
    cache: "/var/lib/drill-acme"
  tenancy:
    enable: true
    storage: "/var/lib/drill/tenants.json"
  admin:
    enable: true
    token: "super-secret-admin-token"
