// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/DragonSecurity/drill/internal/server"
	"github.com/DragonSecurity/drill/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateApp(cfg string) (*server.DrillServer, error) {
	viper, err := server.NewConfig(cfg)
	if err != nil {
		return nil, err
	}
	options, err := server.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	loggerOptions, err := logger.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.NewLogger(loggerOptions)
	if err != nil {
		return nil, err
	}
	drillServer := server.NewDrillServer(options, zapLogger)
	return drillServer, nil
}

// wire.go:

var providerSet = wire.NewSet(logger.ProviderSet, server.ProviderSet)
