name: Build & Publish Release Binaries

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
          cache: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.9.0"
          cache: "npm"
          cache-dependency-path: |
            web/drill/yarn.lock

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install project tools & deps
        run: |
          make install_dependencies

      - name: Build multi-arch release
        run: |
          make release

      - name: List artifacts
        run: ls -lah build/release || true

      - name: Upload artifacts to workflow
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: build/release/*

      - name: Publish assets to GitHub Release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: build/release/*
          make_latest: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
