name: Build & Publish Release Binaries

on:
  release:
    types: [published]
  push:
    tags:
      - "v*"

permissions:
  contents: write   # required to create/update releases & upload assets

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: "0"
      # speed up go
      GOMODCACHE: ${{ runner.tool_cache }}/go/pkg/mod

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            web/drill/package-lock.json
            web/drill/npm-shrinkwrap.json

      - name: Install system deps (optional)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install project tools & deps
        run: |
          make install_dependencies

      - name: Build multi-arch release
        run: |
          make release
        # If your Makefile needs a clean slate each run, uncomment:
        #  make clean && make release

      - name: Show release artifacts
        run: ls -lah build/release || true

      # Upload as workflow artifact (handy for debugging / re-use between jobs)
      - name: Upload artifacts to workflow
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: build/release/*

      # Publish to GitHub Release (creates one if triggered by tag push)
      - name: Publish assets to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        with:
          files: build/release/*
          # If triggered by a tag push and no release exists, this will create one:
          make_latest: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
